# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goregraph < Formula
  desc "Local deterministic code intelligence for safer AI-assisted development"
  homepage "https://github.com/gorecodecom/goregraph"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gorecodecom/goregraph/releases/download/v0.4.0/goregraph_Darwin_x86_64.tar.gz"
      sha256 "0f108f0a83701339d49b9835949e948398b3c8ff1396867167dcd381c05fece7"

      define_method(:install) do
        bin.install "goregraph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gorecodecom/goregraph/releases/download/v0.4.0/goregraph_Darwin_arm64.tar.gz"
      sha256 "a1082954af690a08435718946f334eacad8c1ff44b2b8b688c42f5ac6c7f0677"

      define_method(:install) do
        bin.install "goregraph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gorecodecom/goregraph/releases/download/v0.4.0/goregraph_Linux_x86_64.tar.gz"
      sha256 "e59eacb9c8f8d25dfe764c1dfc53e3e3bf24450a0551ac2015d4ba4844820ab7"
      define_method(:install) do
        bin.install "goregraph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gorecodecom/goregraph/releases/download/v0.4.0/goregraph_Linux_arm64.tar.gz"
      sha256 "b9f4a613bc6a5d6bb875ea84ee10b44ea2e3071679164095bda99e9ca1beed4b"
      define_method(:install) do
        bin.install "goregraph"
      end
    end
  end

  test do
    system bin/"goregraph", "version"
  end
end
