# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goregraph < Formula
  desc "Local deterministic code intelligence for safer AI-assisted development"
  homepage "https://github.com/gorecodecom/goregraph"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gorecodecom/goregraph/releases/download/v0.2.0/goregraph_Darwin_x86_64.tar.gz"
      sha256 "77de67cb90235309dc4e79a67771a8b97d3c8e161047da27e70372517f8983df"

      define_method(:install) do
        bin.install "goregraph"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gorecodecom/goregraph/releases/download/v0.2.0/goregraph_Darwin_arm64.tar.gz"
      sha256 "541962a8a1f29fccdddab950146815b7649e1ed386d4a229f45026008c4406df"

      define_method(:install) do
        bin.install "goregraph"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gorecodecom/goregraph/releases/download/v0.2.0/goregraph_Linux_x86_64.tar.gz"
      sha256 "f8f014bfc661210e5b732cf0bfc608414cdbbea4794790af0a2ef12a036bc65a"
      define_method(:install) do
        bin.install "goregraph"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gorecodecom/goregraph/releases/download/v0.2.0/goregraph_Linux_arm64.tar.gz"
      sha256 "71b54de8e5f6f1f32e0d2fee34693cfea3cd58533a44cc1cb4551ae14487afd1"
      define_method(:install) do
        bin.install "goregraph"
      end
    end
  end

  test do
    system bin/"goregraph", "version"
  end
end
